### ISSUE TITLE
Add "pgctl status --json"

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/pgctl#146]
We currently use pidfiles to signal services (e.g. we have a service which watches Python files and sends HUP to apache when a file is changed).

pidfiles suck; it'd be great if we could use pgctl to get the PID.

We discussed adding a "kill" or "signal" command to pgctl, but a nice start would just be adding JSON output to `pgctl status --json`.

**Comment by asottile** [comment]
Sg2m. Pgctl should reasonably be the source of truth for these things
