### ISSUE TITLE
missing coverage for PGCTL_DEBUG in poll-ready

### ISSUE THREAD

**Issue by asottile** [Yelp/pgctl#178]
perhaps due to #177 CC @bchess

This line: https://github.com/Yelp/pgctl/blob/d47103bf4d2f8c79f4d9995a3fb5e235c38c1e64/pgctl/poll_ready.py#L107

**Comment by bchess** [comment]
was already true before my change, e.g a4d6acebe232de32654b72d671b48be1d7a10906

**Comment by asottile** [comment]
Seems to have passed here: https://circleci.com/gh/Yelp/pgctl/207

**Comment by bchess** [comment]
Seems flakey. I've run `make test` several times and gotten different results on this one line, both with and without my change

**Comment by asottile** [comment]
Thanks for looking intro this :)  I incorrectly assumed that they were related given the similarity in subject and the circle build becoming failing.

**Comment by bchess** [comment]
No prob - I'm still staring at a bit to see if I can figure out why..

**Comment by 0xngold** [comment]
@asottile this seems to have been true since #174 was merged. @bukzor and I haven't figured why moving that statement started causing issues. Originally we suspected something about test parallelism and coverage.
