### ISSUE TITLE
Config file loads have py2/3 text/bytes problems

### ISSUE THREAD

**Issue by 0xngold** [Yelp/pgctl#203]
pgctl.yaml is loaded by pgctl in "text" mode. This is ambiguous / scary in py3/py2 cross compatible code, because
* in Python 3, a file in "text" mode means read() yields text
* in Python 2, a file in "text" mode means read() yields bytes/str

Scary, but not necessarily wrong... right? Unfortunately, in Python 2, the config keys in the defaults dictionary are text, because unicode literals are on. This means that merging any key with a default will fail, because the default is text, and the one loaded from the file is bytes.

**Comment by chriskuehl** [comment]
probably just want to use `io.open` instead of `open` so you get text on both

**Comment by 0xngold** [comment]
The statement about key merging bring broken is not correct (problem that started this investigation was caused by a semantic yaml indentation error in a consuming application; ugh).

```
Python 2.7.6 (default, Jun 23 2016, 21:30:43)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {u'a': 1}
>>> type('a')
<type 'str'>
>>> type(u'a')
<type 'unicode'>
>>> d['a']
1
>>> d[u'a']
1
>>>
```

Why does this actually work correctly...?
```
>>> hash('a')
12416037344
>>> hash(u'a')
12416037344
```
