### ISSUE TITLE
Remove me from circle-ci configuration

### ISSUE THREAD

**Issue by asottile** [Yelp/pgctl#206]
I continue to get failure emails and I don't have permission on circle ci to remove myself (perhaps because I'm not a collaborator on this project?)

@tomelm any ideas here?

**Comment by tomelm** [comment]
Hmm, I'll take a look but I don't see any obvious settings to remove you from that.

**Comment by asottile** [comment]
Maybe if you add me as a collaborator, I can attempt to remove myself, then you can remove me as a collaborator?

**Comment by tomelm** [comment]
Sure, let's try that.

**Comment by asottile** [comment]
Ok, accepted and now the "Edit Yelp/pgctl" page allows me to view it and Unfollow.

I've clicked Unfollow so now you can remove me @tomelm!  Thanks again :D
