### ISSUE TITLE
It should be possible to specify an alternate to pgctl.yaml

### ISSUE THREAD

**Issue by firba1** [Yelp/pgctl#210]
Currently, if a pgctl invocation runs in a dir with a pgctl.yaml (or .json, .conf, .ini), there is no way to prevent pgctl from loading that config or substituting your own. This should be supported, probably with a command line argument (e.g. "--config").

**Comment by magicmark** [comment]
(internal ticket: CORESERV-9210)

**Comment by firba1** [comment]
Fixed by PR #211
