### ISSUE TITLE
how to tag releases file

### ISSUE THREAD

**Issue by kentwills** [Yelp/pgctl#57]
Suggested content

1. ``git checkout upstream/master -b {{branch}}``
2. bump setup.py
2. bump doc versions in docs/source/conf.py
3. ``git commit -m "{{version}}"``
4. ``git tag {{version}}``
5. ``git push --tags`` (push tags to upstream)
6. ``git push origin HEAD``
7. Create a pull request

**Comment by bukzor** [comment]
Put this in RELEASE.md and note that it's for maintainers only.
